"""
report.py — Sakoon AI
PDF wellness report generation via fpdf2. Implements the layout from
DESIGN.md §11 exactly:
  - A4, 20mm margins
  - Header band: --color-primary (#5B8AA6), 28mm, white text
  - Section headers: --color-primary-dark (#3F6C86), 13pt bold + 0.75pt
    --color-secondary (#8FBFA6) underline rule
  - Body: 11pt, 1.4 line spacing, --color-text-primary (#2B2B2B)
  - Disclaimer box: --color-warning-bg (#FBF1E1), 9pt italic
  - Footer: 8pt gray, centered, page X of Y
  - Urdu text: NotoNastaliqUrdu-Regular.ttf embedded via add_font()
  - Section order per IDEA.md §9:
      Header → Patient Info → Disclaimer → Session Summary →
      Symptoms & Triggers → Self-Care Plan → When to Seek Help → Footer

Public API:
  build_report(profile, session_data, narrative) -> bytes
  build_session_data(session_state) -> dict
"""

import os
from datetime import datetime, timezone
from pathlib import Path
from fpdf import FPDF
from fpdf.enums import XPos, YPos

# ── Colors (DESIGN.md §15) ───────────────────────────────────────────────────
PRIMARY         = (91,  138, 166)   # #5B8AA6
PRIMARY_DARK    = (63,  108, 134)   # #3F6C86
SECONDARY       = (143, 191, 166)   # #8FBFA6
TEXT_PRIMARY    = (43,  43,  43)    # #2B2B2B
TEXT_SECONDARY  = (107, 107, 107)   # #6B6B6B
TEXT_INVERSE    = (255, 255, 255)   # #FFFFFF
WARNING_BG      = (251, 241, 225)   # #FBF1E1
WARNING_BORDER  = (201, 138, 46)    # #C98A2E
SURFACE         = (255, 255, 255)   # #FFFFFF

# ── Font paths ────────────────────────────────────────────────────────────────
from sakoon.core.paths import FONT_URDU as _FONT_URDU_PATH
FONT_URDU = str(_FONT_URDU_PATH)
# ── Helpers ───────────────────────────────────────────────────────────────────

def _has_urdu(text: str) -> bool:
    """Return True if text contains Arabic-range Unicode (Urdu script)."""
    import re
    return bool(re.search(r'[\u0600-\u06FF\u0750-\u077F]', text or ""))


def _safe_str(val) -> str:
    """Convert any value to a printable string, handling None gracefully."""
    if val is None:
        return "-"
    if isinstance(val, list):
        return ", ".join(str(v) for v in val) if val else "-"
    return str(val)


class _SakoonPDF(FPDF):
    """FPDF subclass with Sakoon styling helpers."""

    def __init__(self, total_pages_ref: list):
        super().__init__(orientation="P", unit="mm", format="A4")
        self._total_pages_ref = total_pages_ref
        self.set_margins(20, 20, 20)
        self.set_auto_page_break(auto=True, margin=20)
        # Register fonts
        # Inter — load as DejaVuSans (available everywhere, close enough for report)
        # Use built-in Helvetica for Latin body text (reliable across environments)
        if os.path.exists(FONT_URDU):
            self.add_font("NotoNastaliqUrdu", "", FONT_URDU)
            self._urdu_available = True
        else:
            self._urdu_available = False

    def header(self):
        pass  # custom header drawn in build_report()

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*TEXT_SECONDARY)
        total = self._total_pages_ref[0] if self._total_pages_ref else "?"
        self.cell(
            0, 10,
            f"Generated by Sakoon AI  |  {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}  |  Page {self.page_no()} of {total}",
            align="C",
        )

    def draw_header_band(self, generated_date: str):
        """Full-width header band per DESIGN.md §11."""
        self.set_fill_color(*PRIMARY)
        self.rect(0, 0, 210, 28, "F")  # A4 width = 210mm, height = 28mm
        # App name
        self.set_font("Helvetica", "B", 18)
        self.set_text_color(*TEXT_INVERSE)
        self.set_xy(20, 8)
        self.cell(130, 10, "Sakoon AI - Wellness Report", align="L")
        # Date right-aligned
        self.set_font("Helvetica", "", 10)
        self.set_xy(0, 12)
        self.cell(190, 8, generated_date, align="R")
        self.set_xy(20, 28)  # reset cursor below band

    def section_header(self, title: str):
        """Section header per DESIGN.md §11: 13pt bold PRIMARY_DARK + underline."""
        self.ln(6)
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(*PRIMARY_DARK)
        self.cell(0, 8, title, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        # 0.75pt secondary-color underline rule
        x = self.get_x()
        y = self.get_y()
        self.set_draw_color(*SECONDARY)
        self.set_line_width(0.3)
        self.line(20, y, 190, y)
        self.ln(3)

    def body_text(self, text: str, label: str = ""):
        """11pt body text. Handles Urdu via NotoNastaliqUrdu if available."""
        self.set_line_width(0.2)
        is_urdu = _has_urdu(text)
        if label:
            self.set_font("Helvetica", "B", 11)
            self.set_text_color(*PRIMARY_DARK)
            self.cell(45, 7, f"{label}:", new_x=XPos.RIGHT, new_y=YPos.TOP)

        if is_urdu and self._urdu_available:
            self.set_font("NotoNastaliqUrdu", "", 14)
        else:
            self.set_font("Helvetica", "", 11)
        self.set_text_color(*TEXT_PRIMARY)
        x_start = self.get_x()
        w = 190 - (x_start - 20)
        self.multi_cell(
            w, 7, _safe_str(text), align="R" if is_urdu else "L",
            new_x=XPos.LMARGIN, new_y=YPos.NEXT
        )

    def disclaimer_box(self, text: str):
        """DESIGN.md §11: warning-bg box, rounded corners, 9pt italic."""
        self.ln(4)
        x, y = self.get_x(), self.get_y()
        w = 170
        # Background
        self.set_fill_color(*WARNING_BG)
        self.set_draw_color(*WARNING_BORDER)
        self.set_line_width(0.3)
        self.rect(x, y, w, 14, "FD")
        # Text
        self.set_font("Helvetica", "I", 9)
        self.set_text_color(*TEXT_PRIMARY)
        self.set_xy(x + 4, y + 3)
        self.multi_cell(w - 8, 5, text, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.ln(2)

    def bullet_list(self, items: list):
        """Render a list of items as bullet points."""
        if not items:
            self.body_text("-")
            return
        for item in items:
            self.set_font("Helvetica", "", 11)
            self.set_text_color(*TEXT_PRIMARY)
            self.cell(6, 7, "-")
            is_urdu = _has_urdu(item)
            if is_urdu and self._urdu_available:
                self.set_font("NotoNastaliqUrdu", "", 14)
            self.multi_cell(164, 7, _safe_str(item), new_x=XPos.LMARGIN, new_y=YPos.NEXT)


# ── Public: build session data dict ──────────────────────────────────────────

def build_session_data(session_state) -> dict:
    """
    Extract a clean report dict from st.session_state.
    All fields have graceful None defaults.
    """
    p = session_state.get("profile", {})
    return {
        "name": p.get("name"),
        "email": p.get("email"),
        "phone": p.get("phone"),
        "primary_concern": p.get("primary_concern"),
        "mood_rating": p.get("mood_rating"),
        "symptoms": p.get("symptoms", []),
        "possible_triggers": p.get("possible_triggers", []),
        "risk_flags": p.get("risk_flags", []),
        "conversation_stage": session_state.get("stage", "-"),
        "session_language": session_state.get("lang", "english"),
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
    }


# ── Public: build PDF bytes ───────────────────────────────────────────────────

def build_report(session_data: dict, narrative: str = "") -> bytes:
    """
    Build the PDF wellness report and return the raw bytes.
    Never raises — returns None on failure (caller shows error banner).

    Args:
        session_data: dict from build_session_data()
        narrative: one-paragraph Groq-generated plain text summary (optional)

    Returns:
        PDF bytes, or None on failure.
    """
    try:
        total_pages_ref = [0]
        pdf = _SakoonPDF(total_pages_ref)
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=20)
        total_pages_ref[0] = 1  # single-page for now; updated after build

        generated_date = session_data.get("generated_at", datetime.now(timezone.utc).strftime("%Y-%m-%d"))
        name = _safe_str(session_data.get("name")) or "Your"
        lang = session_data.get("session_language", "english")

        # ── Header band ──────────────────────────────────────────────────────
        pdf.draw_header_band(generated_date)
        pdf.ln(8)

        # ── Disclaimer (top, per DESIGN.md §11) ─────────────────────────────
        pdf.disclaimer_box(
            "This report is for personal reflection only. It is not a medical diagnosis "
            "or clinical assessment. If you are experiencing a mental health crisis, "
            "please contact a licensed professional or call Umang Helpline: 0311-7786264."
        )

        # ── Patient Info ─────────────────────────────────────────────────────
        pdf.section_header("Patient Information")
        pdf.body_text(_safe_str(session_data.get("name")), label="Name")
        pdf.body_text(_safe_str(session_data.get("email")), label="Email")
        pdf.body_text(_safe_str(session_data.get("phone")), label="Phone")
        pdf.body_text(generated_date, label="Session Date")

        # ── Session Summary ──────────────────────────────────────────────────
        pdf.section_header("Session Summary")
        primary_concern = _safe_str(session_data.get("primary_concern"))
        pdf.body_text(primary_concern, label="Primary Concern")
        mood = session_data.get("mood_rating")
        mood_labels = {
            **{i: "Having a hard time" for i in range(1, 4)},
            **{i: "Getting through it" for i in range(4, 7)},
            **{i: "Feeling steady" for i in range(7, 11)},
        }
        mood_text = f"{mood}/10 - {mood_labels.get(mood, '-')}" if mood else "-"
        pdf.body_text(mood_text, label="Mood Today")
        # Narrative paragraph
        if narrative and narrative.strip():
            pdf.ln(3)
            is_narr_urdu = _has_urdu(narrative) and pdf._urdu_available
            if is_narr_urdu:
                pdf.set_font("NotoNastaliqUrdu", "", 14)
            else:
                pdf.set_font("Helvetica", "I", 11)
            pdf.set_text_color(*TEXT_SECONDARY)
            pdf.multi_cell(
                0, 7, narrative.strip(),
                align="R" if is_narr_urdu else "L",
                new_x=XPos.LMARGIN, new_y=YPos.NEXT
            )

        # ── Symptoms & Triggers ──────────────────────────────────────────────
        pdf.section_header("Symptoms & Triggers Noted")
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(*PRIMARY_DARK)
        pdf.cell(0, 7, "Symptoms:", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.bullet_list(session_data.get("symptoms", []))
        pdf.ln(3)
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(0, 7, "Possible Triggers:", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.bullet_list(session_data.get("possible_triggers", []))

        # ── Self-Care Plan ───────────────────────────────────────────────────
        pdf.section_header("Your Self-Care Plan")
        care_items = [
            "Take a few slow, deep breaths when you feel overwhelmed - even 3 breaths can help.",
            "Try to keep a consistent sleep schedule, even if sleep is difficult right now.",
            "Share how you're feeling with someone you trust - you don't have to carry this alone.",
            "Keep this session open - come back to Sakoon AI anytime you need to talk.",
        ]
        pdf.bullet_list(care_items)

        # ── When to Seek Help ────────────────────────────────────────────────
        pdf.section_header("When to Reach Out for More Support")
        support_items = [
            "If your feelings are becoming overwhelming and interfering with daily life.",
            "If you're having thoughts of harming yourself or others.",
            "If you've been struggling for more than two weeks.",
            "Umang Mental Health Helpline (Pakistan): 0311-7786264",
            "You can also reach out to a licensed counsellor or therapist in your area.",
        ]
        pdf.bullet_list(support_items)

        # ── Footer disclaimer ────────────────────────────────────────────────
        pdf.ln(6)
        pdf.disclaimer_box(
            "Sakoon AI is not a substitute for professional mental health care. "
            "Always consult a qualified mental health professional for clinical advice."
        )

        # ── Finalise ─────────────────────────────────────────────────────────
        # fpdf2: pdf.pages is a dict keyed by page number — use len() for the count
        total_pages_ref[0] = len(pdf.pages)
        return bytes(pdf.output())
    except Exception as e:
        from sakoon.core.logging import get_logger
        get_logger(__name__).error("build_report failed: %s", e)
        return None
