"""Database package."""

from sakoon.db.database import (  # noqa: F401
    init_db,
    upsert_user,
    update_user,
    get_or_create_local_user,
    create_auth_user,
    get_user_by_username,
    get_user_by_id,
    session_belongs_to_user,
    create_session,
    update_session,
    close_session,
    log_message,
    get_messages,
    delete_last_assistant_message,
    upsert_snapshot,
    get_snapshot,
    get_recent_sessions,
    add_mood_log,
    get_mood_logs,
    add_journal_entry,
    get_journal_entries,
    get_mood_daily_averages,
    get_activity_daily_counts,
    get_active_days,
    get_insights_totals,
    DB_PATH,
)
