[theme]
base = "light"
primaryColor = "#0D9488"
backgroundColor = "#F0FDFA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#134E4A"
font = "sans serif"

[client]
showErrorDetails = false
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
